title:             Hongzhuo Liang
tagline:           PhD student at University of Hamburg, Faculty of Mathematics, Informatics and Natural Science, Department Informatics, Group TAMS
show_downloads:    false
baseurl:           ""
locale:            "en"
# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

permalink: /blog/:year/:month/:day/:title
